[package]
name = "zenithds"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
axum = "0.8.1"
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0.217", features = ["derive"] }
regex = "1.11.1"